### ISSUE TITLE
Do not use cache on website settings when installing plugin

### ISSUE THREAD

**Issue by Pegasuz** [studioemma/pimcore-plugin-PluginInstallationStep#2]
When installing the plugin, the cache on the website settings is also used, which fails the isInstalled() step.

See commit: 
https://github.com/studioemma/pimcore-plugin-PluginInstallationStep/commit/9e9173f3dd2dadeca7ba857e6cd58b920706c983

Proposed solution: differentiate between installation of plugin and normal check of IsInstalled() (every pageload).

**Comment by BlackIkeEagle** [comment]
fixed in https://github.com/studioemma/pimcore-plugin-PluginInstallationStep/commit/2d72b8f5c6010c44f50cd3fce60d4e8858d10508
